# This plugin detects jar changes in plugins and reloads with plugmanX the plugins, useful for dev
# !!! You should not use the plugin in production you could have issues !!!
# Made by SuperMax_8 https://www.spigotmc.org/members/supermax_8.479560/

# If the plugin is activated or not, set it to false in production to avoid issue
working: true

# The list of plugins you want to auto-reload
plugins:
  - "ExamplePlugin1"